# Generated by Django 5.2.14 on 2026-05-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('dob', models.DateField()),
                ('Gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=1)),
            ],
        ),
    ]
