# Generated by Django 5.2.14 on 2026-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App03', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('Gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=1)),
            ],
        ),
    ]
